[main]
num_threads = 12
dt_pde = 0.020000
simulation_time = 1000.000000
abort_on_no_activity = 1
use_adaptivity = 0

[ode_solver]
dt = 0.020000
use_gpu = 0
gpu_id = 0
library_file = shared_libs/libtt3_mixed_with_activations_times.so

[stimulus]
main_function = set_stim_from_file
library_file = ./shared_libs/libdefault_stimuli.so
start = 0
duration = 2.0
current = -38.0
stim_file = local_stims/Patient_10_endocardium_points.pts

[domain]
main_function = initialize_grid_with_hu_mesh_with_scar
library_file = ./shared_libs/libdefault_domains.so
name = HU Mesh 3D
original_discretization = 500.0
desired_discretization = 500.0
num_volumes = 1210229
mesh_file = meshes/Patient_10.alg
num_extra_fields = 11
start_dx = 500.000000
start_dy = 500.000000
start_dz = 500.000000

[assembly_matrix]
main_function = anisotropic_sigma_assembly_matrix_for_hu_mesh
init_function = set_initial_conditions_fvm
;sigma_C = 1.0
sigma_factor = 0.0
sigma_l = 0.000313
sigma_t = 0.000313 / 10
sigma_n = 0.000313 / 10
fibers_in_mesh = true
number_layers_bz = 0

[update_monodomain]
main_function = update_monodomain_default
library_file = ./shared_libs/libdefault_update_monodomain.so

[linear_system_solver]
main_function = conjugate_gradient
init_function = init_conjugate_gradient
end_function = end_conjugate_gradient
tolerance = 1e-9
use_preconditioner = no
use_gpu = no
max_iterations = 200

[extra_data]
main_function = set_extra_data_for_scv_mesh

[save_result]
main_function = save_ecg_data
init_function = init_save_ecg_data
end_function = end_save_ecg_data
library_file = ./shared_libs/libdefault_save_mesh.so
print_rate = 100
output_dir = ./outputs/TCC_matheus/P10
binary = true
mesh_format = ensight
mesh_print_rate = 100
file_prefix = V
abort_on_no_activity = true
last_stimulus_time = 5112.0
vm_threshold = -86.0

[save_state]
main_function = save_simulation_state_with_activation_times
input_dir = ./outputs/P10_estimulo_Endo/

[calc_ecg]
main_function = pseudo_bidomain
init_function = init_pseudo_bidomain
end_function = end_pseudo_bidomain
calc_rate = 10
lead1 = 0,0,0
sigma_b = 20
use_gpu = false
filename = ./outputs/P10_new_Endo_ecg/ecg.txt

